import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar
    'nav.apply': 'Apply Now',
    'nav.about': 'About Us',
    
    // Hero
    'hero.title': 'Fast, Flexible Capital for Your Business',
    'hero.subtitle': 'Get the funding you need with personalized service. Apply in minutes, receive your offer, and access funds within 24-48 hours.',
    'hero.animated.capital': 'Capital',
    'hero.animated.moves': ' that moves at your ',
    'hero.animated.speed': 'speed',
    'hero.cta': 'Get Your Offer',
    'hero.instant': 'Instant Decisions',
    'hero.instantSub': 'Get approved in minutes',
    'hero.amount': '$10K - $250K',
    'hero.amountSub': 'Flexible funding amounts',
    'hero.funding': '24-48 Hour Funding',
    'hero.fundingSub': 'Fast access to capital',
    'hero.service': 'Personal Service',
    'hero.serviceSub': 'Dedicated support team',
    'hero.typicalFunding': 'Typical Funding Amount',
    'hero.appTime': 'Application Time',
    'hero.appTime.value': '10-15 minutes',
    'hero.decisionTime': 'Decision Time',
    'hero.decisionTime.value': 'Instant - 4 hours',
    'hero.fundingSpeed': 'Funding Speed',
    'hero.fundingSpeed.value': '24-48 hours',
    'hero.approvalRate': 'Typical Approval Rate',
    
    // How It Works
    'how.title': 'How It Works',
    'how.subtitle': 'Get the capital you need in four simple steps—fast, transparent, and hassle-free',
    'how.step1.title': 'Apply online in minutes',
    'how.step1.desc': 'Provide basic information about your business and get a decision in as fast as minutes. Applying won\'t impact your credit score.',
    'how.step2.title': 'Receive your instant funding offer',
    'how.step2.desc': 'Get approved and see your funding offer immediately. Review terms, factor rates, and payment schedules tailored to your business.',
    'how.step3.title': 'Access funds within 24-48 hours',
    'how.step3.desc': 'Once you accept, funds are deposited directly into your business account the next business day—often within 24 hours.',
    'how.step4.title': 'Make automatic repayments',
    'how.step4.desc': 'Repay automatically based on a percentage of your daily credit card sales. Higher sales days mean higher payments, slower days mean lower payments.',
    
    // Use Capital
    'capital.title': 'Deploy Your Capital Strategically',
    'capital.subtitle': 'Whether you\'re scaling, investing, or seizing an opportunity, your capital can fuel growth across your business',
    'capital.payroll.title': 'Payroll & Hiring',
    'capital.payroll.desc': 'Bring on the talent you need to scale your operations and meet growing demand.',
    'capital.expansion.title': 'Business Expansion',
    'capital.expansion.desc': 'Open new locations, expand your footprint, or upgrade to a larger facility.',
    'capital.inventory.title': 'Inventory & Stock',
    'capital.inventory.desc': 'Purchase inventory in bulk, take advantage of supplier discounts, or prepare for peak season.',
    'capital.marketing.title': 'Marketing Campaigns',
    'capital.marketing.desc': 'Invest in advertising, digital marketing, or promotional campaigns to drive new customers.',
    'capital.equipment.title': 'Equipment & Technology',
    'capital.equipment.desc': 'Upgrade machinery, purchase new equipment, or invest in technology that improves efficiency.',
    'capital.vendor.title': 'Vendor Payments',
    'capital.vendor.desc': 'Pay suppliers on time, negotiate better terms, or take advantage of early payment discounts.',
    'capital.helpTitle': 'Not sure what you need? We\'re here to help.',
    'capital.helpDesc': 'Our dedicated team works with you to understand your business goals and find the right funding solution. Get personalized guidance every step of the way.',
    'capital.hours': 'Monday - Friday, 8am - 8pm EST',
    
    // Guides
    'guides.title': 'Useful Guides & Resources',
    'guides.subtitle': 'Everything you need to know about merchant cash advances and business funding',
    'guides.calculator.title': 'MCA Cost Calculator',
    'guides.calculator.desc': 'Calculate the true cost of your merchant cash advance and compare factor rates.',
    'guides.qualification.title': 'Qualification Requirements',
    'guides.qualification.desc': 'Pre-qualify and find out what lenders look for to improve your approval chances.',
    'guides.repayment.title': 'Revenue-Based Repayment Guide',
    'guides.repayment.desc': 'Understand how daily percentage payments flex with your business performance.',
    'guides.open': 'Open Tool',
    'guides.learn': 'Learn more',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Get answers to common questions about our merchant cash advance program',
    'faq.q1': 'How fast can I get my funds?',
    'faq.a1': 'Funding times vary based on several factors, including application completeness and approval processing. Many qualified applicants receive funding within 1-3 business days of approval. We work diligently to process applications as quickly as possible while maintaining our underwriting standards.',
    'faq.q2': 'What is a factor rate?',
    'faq.a2': 'A factor rate is a decimal figure used to calculate the total repayment amount. Rather than expressing cost as an annual percentage rate, the factor rate is multiplied by your advance amount to determine your total payback. For example, a factor rate of 1.25 on a $10,000 advance would result in a total repayment of $12,500.',
    'faq.q3': 'What are the repayment terms?',
    'faq.a3': 'Repayment is structured based on your business\'s cash flow, typically through automatic daily or weekly remittances. The specific schedule is determined during the approval process and outlined in your agreement. Terms are designed to align with your revenue patterns.',
    'faq.q4': 'What do I need to apply?',
    'faq.a4': 'Application requirements typically include basic business information, recent bank statements, and identification documentation. Our application process is designed to be straightforward. A representative can provide a complete list of required materials based on your specific situation.',
    'faq.q5': 'How much can I qualify for?',
    'faq.a5': 'Qualification amounts vary based on multiple factors, including your business\'s financial performance, time in operation, and cash flow patterns. We evaluate each application individually to determine an appropriate amount that aligns with your business needs and capacity.',
    'faq.q6': 'I have bad credit. Can I still qualify?',
    'faq.a6': 'We evaluate applications holistically, considering various aspects of your business beyond personal credit scores. While credit history is one factor, we also assess business performance, cash flow, and other relevant criteria. We encourage you to apply to learn about your options.',
    'faq.q7': 'Are there hidden fees?',
    'faq.a7': 'All costs are disclosed in your agreement documentation prior to acceptance. We maintain transparency in our fee structure. Please review all agreement terms carefully and ask questions about any items requiring clarification before proceeding.',
    'faq.q8': 'What happens on slow days?',
    'faq.a8': 'Repayment structures are designed with business fluctuations in mind. The specific provisions regarding variable revenue periods are detailed in your agreement. We recommend discussing your business\'s seasonal or cyclical patterns with a representative during the application process.',
    'faq.q9': 'How is this different from a bank loan?',
    'faq.a9': 'Our financing solutions differ from traditional bank loans in several ways, including underwriting criteria, funding speed, repayment structure, and collateral requirements. We focus on your business\'s performance and cash flow rather than exclusively on credit scores and extensive documentation requirements.',
    'faq.q10': 'Isn\'t this expensive?',
    'faq.a10': 'Cost varies based on individual circumstances and the specific product. When evaluating financing options, consider factors beyond cost alone, including access speed, qualification requirements, and alignment with your business needs. We encourage you to compare total costs and terms across all options available to you.',
    'faq.stillQuestions': 'Still have questions?',
    'faq.callUs': 'Call Us: (864) 729-3358',
    
    // CTA
    'cta.title': 'Ready to grow?',
    'cta.subtitle': 'Want to learn more?\nExplore our Resources and Guides.',
    'cta.button': 'Get started',
    'cta.minutes': '10-15 Minutes',
    'cta.minutesSub': 'Quick application process',
    'cta.instant': 'Instant Decision',
    'cta.instantSub': 'Get approved in minutes',
    'cta.hours': '24-48 Hours',
    'cta.hoursSub': 'Funds in your account',
    
    // Footer
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.howItWorks': 'How It Works',
    'footer.reviews': 'Reviews',
    'footer.blog': 'Blog',
    'footer.resources': 'Resources',
    'footer.faq': 'FAQ',
    'footer.calculator': 'Calculator',
    'footer.caseStudies': 'Case Studies',
    'footer.support': 'Help Center',
    'footer.contact': 'Contact',
    'footer.hours': 'Mon-Fri, 8am-8pm EST',
    'footer.description': 'Fast, flexible merchant cash advances with personalized service and transparent terms.',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.disclosures': 'Disclosures',
    'footer.disclaimer': 'Delt provides merchant cash advances, which are not loans. Merchant cash advances are business-to-business transactions and are not subject to the same regulations as consumer loans. Approval and terms based on business performance. For demonstration purposes only.',
    
    // About Page
    'about.title': 'About Delt',
    'about.subtitle': 'Empowering businesses with fast, flexible funding solutions',
    'about.hero.title': 'We\'re on a mission to democratize access to business capital',
    'about.hero.desc': 'Founded in 2020, Delt has helped thousands of small and medium-sized businesses access the capital they need to grow, without the traditional barriers of bank financing.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To provide fast, transparent, and flexible funding solutions that help businesses seize opportunities and overcome challenges.',
    'about.values.title': 'Our Values',
    'about.values.speed': 'Speed',
    'about.values.speedDesc': 'Decisions in minutes, funding in days',
    'about.values.transparency': 'Transparency',
    'about.values.transparencyDesc': 'No hidden fees, clear terms',
    'about.values.flexibility': 'Flexibility',
    'about.values.flexibilityDesc': 'Payments that adapt to your business',
    'about.values.service': 'Service',
    'about.values.serviceDesc': 'Personalized support every step',
    'about.stats.funded': 'Businesses Funded',
    'about.stats.capital': 'Capital Deployed',
    'about.stats.approval': 'Approval Rate',
    'about.stats.satisfaction': 'Customer Satisfaction',
    'about.team.title': 'Built by fintech experts',
    'about.team.desc': 'Our team brings decades of experience from leading financial institutions and technology companies.',
    'about.cta': 'Ready to get started?',
    'about.apply': 'Apply Now',
    
    // PreQualification Quiz
    'quiz.q1.question': 'What is your average monthly revenue?',
    'quiz.q1.subtitle': 'This helps us determine your funding capacity',
    'quiz.q1.opt1': 'Under $10,000/month',
    'quiz.q1.opt2': '$10,000 - $25,000/month',
    'quiz.q1.opt3': '$25,000 - $50,000/month',
    'quiz.q1.opt4': '$50,000 - $100,000/month',
    'quiz.q1.opt5': '$100,000+/month',
    
    'quiz.q2.question': 'How long has your business been operating?',
    'quiz.q2.subtitle': 'Established businesses typically qualify for better terms',
    'quiz.q2.opt1': 'Less than 6 months',
    'quiz.q2.opt2': '6-12 months',
    'quiz.q2.opt3': '1-2 years',
    'quiz.q2.opt4': '2-5 years',
    'quiz.q2.opt5': '5+ years',
    
    'quiz.q3.question': 'What is your monthly credit card processing volume?',
    'quiz.q3.subtitle': 'MCAs are repaid through card sales, so this is crucial',
    'quiz.q3.opt1': 'No credit card processing',
    'quiz.q3.opt2': 'Under $5,000/month',
    'quiz.q3.opt3': '$5,000 - $15,000/month',
    'quiz.q3.opt4': '$15,000 - $40,000/month',
    'quiz.q3.opt5': '$40,000+/month',
    
    'quiz.q4.question': 'What is your personal credit score range?',
    'quiz.q4.subtitle': 'Used for approval and pricing decisions',
    'quiz.q4.opt1': 'Under 550',
    'quiz.q4.opt2': '550-599',
    'quiz.q4.opt3': '600-649',
    'quiz.q4.opt4': '650-699',
    'quiz.q4.opt5': '700+',
    
    'quiz.q5.question': 'How much funding do you need?',
    'quiz.q5.subtitle': 'We offer advances from $10,000 to $250,000',
    'quiz.q5.opt1': '$10,000 - $25,000',
    'quiz.q5.opt2': '$25,000 - $50,000',
    'quiz.q5.opt3': '$50,000 - $100,000',
    'quiz.q5.opt4': '$100,000 - $150,000',
    'quiz.q5.opt5': '$150,000+',
    
    'quiz.q6.question': 'What will you use the funds for?',
    'quiz.q6.subtitle': 'Understanding your needs helps us serve you better',
    'quiz.q6.opt1': 'Inventory Purchase',
    'quiz.q6.opt2': 'Equipment or Technology',
    'quiz.q6.opt3': 'Marketing & Growth',
    'quiz.q6.opt4': 'Working Capital',
    'quiz.q6.opt5': 'Business Expansion',
    'quiz.q6.opt6': 'Other Business Needs',
    
    'quiz.progress': 'Question {{current}} of {{total}}',
    'quiz.next': 'Next',
    'quiz.previous': 'Previous',
    'quiz.seeResults': 'See Results',
    
    // Quiz Results
    'results.title': 'Congratulations! You Pre-Qualify',
    'results.subtitle': 'Based on your answers, we estimate you qualify for:',
    'results.fundingEstimate': 'Funding Estimate',
    'results.to': 'to',
    'results.nextSteps': 'Next Steps',
    'results.step1': 'Complete your full application',
    'results.step2': 'Connect your bank and card processor',
    'results.step3': 'Receive your final offer in minutes',
    'results.step4': 'Funds in your account within 24-48 hours',
    'results.benefits': 'Your Benefits',
    'results.benefit1': 'Instant Decision',
    'results.benefit1desc': 'Response in minutes',
    'results.benefit2': 'No Paperwork',
    'results.benefit2desc': '100% digital process',
    'results.benefit3': 'Flexible Payments',
    'results.benefit3desc': 'Based on your sales',
    'results.benefit4': 'Fast Funding',
    'results.benefit4desc': '24-48 hours',
    'results.continue': 'Continue to Application',
    
    // Application Form
    'app.businessInfo': 'Business Information',
    'app.businessInfo.desc': 'Tell us about your business',
    'app.ownerInfo': 'Owner Information',
    'app.ownerInfo.desc': 'Primary owner details',
    'app.fundingDetails': 'Funding Details',
    'app.fundingDetails.desc': 'Amount and use of funds',
    'app.bankConnection': 'Bank Connection',
    'app.bankConnection.desc': 'Secure data connection',
    'app.documents': 'Documents',
    'app.documents.desc': 'Upload required documents',
    'app.review': 'Review & Sign',
    'app.review.desc': 'Review and complete',
    
    'app.businessLegalName': 'Business Legal Name',
    'app.businessDBA': 'DBA/Trade Name',
    'app.businessAddress': 'Business Address',
    'app.businessCity': 'City',
    'app.businessState': 'State',
    'app.businessZip': 'ZIP Code',
    'app.businessPhone': 'Business Phone',
    'app.businessEIN': 'EIN (Employer Identification Number)',
    'app.industry': 'Industry',
    'app.timeInBusiness': 'Time in Business',
    'app.monthlyRevenue': 'Monthly Revenue',
    'app.creditCardProcessing': 'Credit Card Volume',
    'app.creditScore': 'Credit Score Range',
    
    'app.ownerFullName': 'Owner Full Name',
    'app.ownerEmail': 'Email Address',
    'app.ownerPhone': 'Phone Number',
    'app.ownerAddress': 'Address',
    'app.ownerCity': 'City',
    'app.ownerState': 'State',
    'app.ownerZip': 'ZIP Code',
    'app.ownerSSN': 'Last 4 Digits of SSN',
    
    'app.requestedAmount': 'Requested Amount',
    'app.intendedUse': 'Intended Use of Funds',
    'app.intendedUse.placeholder': 'Describe how you will use the funds...',
    
    'app.connectBank': 'Connect Bank Account',
    'app.connectBank.desc': 'Securely connect your bank for instant verification',
    'app.connectBank.button': 'Connect with Plaid',
    'app.bankConnected': '✓ Bank Connected',
    'app.creditCardProcessor': 'Credit Card Processor',
    'app.uploadStatements': 'Upload Processor Statements',
    'app.uploadStatements.desc': 'Last 3 months of statements',
    
    'app.governmentID': 'Government-Issued ID',
    'app.governmentID.desc': 'Driver\'s license, passport, etc.',
    'app.voidedCheck': 'Voided Check',
    'app.voidedCheck.desc': 'For bank account verification',
    'app.dragDrop': 'Drag and drop files here, or click to select',
    'app.fileSelected': 'file selected',
    'app.filesSelected': 'files selected',
    
    'app.reviewTitle': 'Review Your Application',
    'app.reviewDesc': 'Please review your information before submitting',
    'app.businessDetails': 'Business Details',
    'app.ownerDetails': 'Owner Details',
    'app.fundingRequest': 'Funding Request',
    'app.amount': 'Amount',
    'app.purpose': 'Purpose',
    
    'app.termsAgree': 'I agree to the Terms and Conditions and authorize Delt to obtain my credit report',
    'app.eSignature': 'Electronic Signature',
    'app.eSignature.placeholder': 'Type your full name',
    'app.eSignature.desc': 'By typing your name above, you electronically agree to the terms of this agreement',
    
    'app.saveProgress': 'Save and Continue Later',
    'app.continue': 'Continue',
    'app.back': 'Back',
    'app.submit': 'Submit Application',
    
    // Success Messages
    'success.title': 'Application Submitted Successfully!',
    'success.subtitle': 'We\'re reviewing your application and will be in touch soon.',
    'success.reference': 'Reference Number',
    'success.whatNext': 'What\'s Next?',
    'success.step1.title': 'Instant Review',
    'success.step1.desc': 'Our team is reviewing your application now',
    'success.step2.title': 'Verification',
    'success.step2.desc': 'We\'ll verify your bank and business information',
    'success.step3.title': 'Final Offer',
    'success.step3.desc': 'You\'ll receive your funding offer in 2-4 hours',
    'success.step4.title': 'Funding',
    'success.step4.desc': 'Accept your offer and receive funds in 24-48 hours',
    'success.contact': 'Questions? Call us at',
    'success.done': 'Done',
    
    // Calculator
    'calc.title': 'MCA Cost Calculator',
    'calc.subtitle': 'Analyze the true cost of your Merchant Cash Advance',
    'calc.advanceAmount': 'Advance Amount',
    'calc.factorRate': 'Factor Rate',
    'calc.paybackAmount': 'Total Payback Amount',
    'calc.totalCost': 'Total Cost',
    'calc.paybackPeriod': 'Payback Period',
    'calc.paybackPeriod.months': 'months',
    'calc.dailyPayment': 'Estimated Daily Payment',
    'calc.effectiveAPR': 'Effective APR',
    'calc.costBreakdown': 'Cost Breakdown',
    'calc.principalAmount': 'Principal Amount',
    'calc.totalInterest': 'Total Interest/Fee',
    'calc.comparison': 'Comparison',
    'calc.traditionalLoan': 'Traditional Loan',
    'calc.mca': 'Merchant Cash Advance',
    'calc.calculate': 'Calculate',
    
    // Additional Quiz/Form UI
    'quiz.complete': 'Complete',
    'quiz.back': 'Back',
    'quiz.startApp': 'Start Your Application',
    'quiz.speakSpecialist': 'Speak with a Specialist',
    
    // Application
    'application.savedAnswers': 'We saved your answers',
    
    // Results Page Detailed
    'results.fundingRange': 'Your Estimated Funding Range',
    'results.basedOnProfile': 'Based on your business profile',
    'results.approvalLikelihood': 'Approval Likelihood',
    'results.factorsConsidered': 'Factors Considered',
    'results.whatHappensNext': 'What Happens Next',
    'results.completeApp': 'Complete Your Application',
    'results.completeApp.time': 'Takes 10-15 minutes',
    'results.instantReview': 'Instant Review',
    'results.instantReview.desc': 'AI analyzes your business in real-time',
    'results.getFunded': 'Get Funded',
    'results.getFunded.desc': 'Money in your account within 24-48 hours',
    'results.disclaimer': 'This is an estimate based on the information provided. Final funding amounts and terms are subject to approval and verification of your business information, credit history, and financial documents.',
    
    // Transition Phase
    'transition.title': 'Great News! You\'re Pre-Qualified',
    'transition.subtitle': 'Let\'s complete your application to finalize your offer',
    'transition.whatWeKnow': 'Here\'s what we already know:',
    'transition.fundingAmount': 'Funding Amount',
    'transition.monthlyRevenue': 'Monthly Revenue',
    'transition.timeInBusiness': 'Time in Business',
    'transition.nextStep': 'Next, we\'ll need:',
    'transition.businessDetails': 'Business Details',
    'transition.ownerInfo': 'Owner Information',
    'transition.bankConnection': 'Bank Connection',
    'transition.autoRedirect': 'Automatically redirecting...',
    
    // Form Steps
    'form.step.basicInfo': 'Basic Information',
    'form.step.ownerInfo': 'Owner Information',
    'form.step.fundingRequest': 'Funding Request',
    'form.step.connectAccounts': 'Connect & Verify Identity',
    'form.step.uploadDocs': 'Upload Documents',
    'form.step.reviewSubmit': 'Review & Submit',
    
    // Industry Options
    'industry.restaurant': 'Restaurant / Food Service',
    'industry.retail': 'Retail',
    'industry.healthcare': 'Healthcare',
    'industry.professional': 'Professional Services',
    'industry.construction': 'Construction',
    'industry.transportation': 'Transportation',
    'industry.manufacturing': 'Manufacturing',
    'industry.technology': 'Technology',
    'industry.hospitality': 'Hospitality',
    'industry.realEstate': 'Real Estate',
    'industry.other': 'Other',
    
    // Funding Uses
    'use.workingCapital': 'Working Capital',
    'use.inventory': 'Inventory Purchase',
    'use.equipment': 'Equipment Purchase',
    'use.marketing': 'Marketing / Advertising',
    'use.expansion': 'Expansion / Growth',
    'use.payroll': 'Payroll',
    'use.debtConsolidation': 'Debt Consolidation',
    'use.renovations': 'Renovations',
    'use.emergency': 'Emergency Expenses',
    'use.other': 'Other',
    
    // Credit Card Processors
    'processor.square': 'Square',
    'processor.clover': 'Clover',
    'processor.toast': 'Toast',
    'processor.stripe': 'Stripe',
    'processor.paypal': 'PayPal',
    'processor.shopify': 'Shopify Payments',
    'processor.authorizenet': 'Authorize.net',
    'processor.firstdata': 'First Data',
    'processor.worldpay': 'Worldpay',
    'processor.other': 'Other',
    
    // MCA Knowledge Center
    'knowledge.title': 'MCA Knowledge Center',
    'knowledge.subtitle': 'Everything you need to know about merchant cash advances',
    'knowledge.howItWorks': 'How It Works',
    'knowledge.howToApply': 'How to Apply',
    'knowledge.managingRepayment': 'Managing Repayment',
    
    // How It Works Tab
    'knowledge.whatIsMCA': 'What is an MCA?',
    'knowledge.whatIsMCA.desc': 'Get capital now. Repay automatically from daily card sales. High sales days = higher payments. Slow days = lower payments.',
    'knowledge.3steps': '3 Simple Steps',
    'knowledge.step1.title': 'Get Funded',
    'knowledge.step1.desc': 'Money in your account in 1-3 days',
    'knowledge.step2.title': 'Auto Repayment',
    'knowledge.step2.desc': 'Fixed % of card sales goes to repayment',
    'knowledge.step3.title': 'Complete',
    'knowledge.step3.desc': 'Holdback stops when paid off',
    'knowledge.keyTerms': 'Key Terms',
    'knowledge.purchaseAmount': 'Purchase Amount',
    'knowledge.purchaseAmount.desc': 'What you receive',
    'knowledge.holdback': 'Holdback %',
    'knowledge.holdback.desc': 'Daily portion toward repayment (10-20%)',
    'knowledge.factorRate': 'Factor Rate',
    'knowledge.factorRate.desc': 'Repayment multiplier (1.15-1.45)',
    'knowledge.goodFit': 'Good Fit?',
    'knowledge.yesIf': 'Yes if you have:',
    'knowledge.yes1': 'Steady credit card sales',
    'knowledge.yes2': 'Retail/restaurant/salon/service business',
    'knowledge.yes3': 'Need fast capital',
    'knowledge.notIdeal': 'Not ideal if:',
    'knowledge.no1': 'Mostly cash business',
    'knowledge.no2': 'Very irregular card sales',
    
    // How to Apply Tab
    'knowledge.youNeed': 'You Need:',
    'knowledge.connectPlaid': 'Connect to Plaid',
    'knowledge.connectPlaid.desc': 'Secure instant bank verification',
    'knowledge.processingStatements': 'Upload Processing Statements',
    'knowledge.processingStatements.desc': 'Last 3-4 months',
    'knowledge.businessInfo': 'Add business info',
    'knowledge.businessInfo.desc': 'ID, legal name, address, tax ID',
    'knowledge.weLookFor': 'We Look For:',
    'knowledge.look1': 'Consistent card volume',
    'knowledge.look2': 'Regular transactions',
    'knowledge.look3': 'Minimal chargebacks',
    'knowledge.quickTips': 'Quick Tips:',
    'knowledge.tip1': 'Have documents ready (PDF/image)',
    'knowledge.tip2': 'Check all details for accuracy',
    'knowledge.tip3': 'Don\'t Apply Everywhere at Once',
    'knowledge.timeline': 'Timeline:',
    'knowledge.timeline.desc': 'Application: 15 min • Review: 24-48 hrs • Funding: 1-3 days',
    
    // Managing Repayment Tab
    'knowledge.firstSteps': 'First Steps',
    'knowledge.first1': 'Verify holdback with processor',
    'knowledge.first2': 'Monitor daily remittances',
    'knowledge.first3': 'Deploy funds strategically',
    'knowledge.knowThis': 'Know This:',
    'knowledge.know1': 'Payments vary daily based on card sales',
    'knowledge.know2': 'Typical payoff: 6-12 months',
    'knowledge.know3': 'Track your balance — Request updates anytime',
    'knowledge.smartMoves': 'Smart Moves',
    'knowledge.useFundsFor': 'Use funds for:',
    'knowledge.use1': 'Inventory',
    'knowledge.use2': 'Equipment',
    'knowledge.use3': 'Marketing',
    'knowledge.use4': 'Cash flow gaps',
    'knowledge.maintain': 'Maintain:',
    'knowledge.maintain.desc': 'Primary processor relationship',
    'knowledge.plan': 'Plan:',
    'knowledge.plan.desc': 'Daily cash flow with holdback factored in',
    'knowledge.futureFunding': 'Future Funding',
    'knowledge.future1': 'Successful repayment = better future terms',
    'knowledge.future2': 'Reapply after 50-75% paid off',
    'knowledge.questions': 'Questions?',
    'knowledge.questions.desc': 'Contact support for balance, holdback, or account help.',

    // Stats Section
    'stats.capitalDelivered': 'working capital delivered',
    'stats.businessesFunded': 'Businesses Funded',
    'stats.satisfactionRate': 'Satisfaction Rate',
    'stats.avgFundingTime': 'Avg. Funding Time',
    'stats.averageAdvance': 'Average Advance',
    'stats.joinText': 'Join the 2,850+ U.S. businesses we\'ve helped with funding and financing solutions tailored to their needs.',
    'stats.industryText': 'From restaurants and retail stores to professional services and healthcare providers, we\'ve partnered with businesses across every industry to fuel their growth with fast, flexible capital.',
    'stats.disclaimer': 'Delt provides commercial funding solutions, including merchant cash advances. Funding may be provided directly by Delt or through third-party funding partners.',

    // Pre-Qualification Section
    'preQual.title': 'See what you\'re approved for.',
    'preQual.subtitle': 'Find out instantly.',
    'preQual.questions': 'Answer 6 questions to unlock:',
    'preQual.probability': 'Your approval probability',
    'preQual.estimatedFunding': 'Estimated funding amount',
    'preQual.expectedPricing': 'Expected pricing',
    'preQual.button': 'Check my amount',
    'preQual.noCredit': 'No credit impact',
    'preQual.instantResults': 'Instant results',
    'preQual.joinText': 'Join 2,850+ businesses who\'ve checked their qualification',

    // Comparison Table
    'comparison.title': 'Why Businesses Choose',
    'comparison.delt': 'Delt',
    'comparison.overLoans': 'Over Traditional Loans',
    'comparison.subtitle': 'See how we stack up against traditional bank loans',
    'comparison.feature': 'Feature',
    'comparison.traditional': 'Traditional Banks',
    'comparison.delt.capital': 'Delt Capital',
    'comparison.getFunded': 'Get Funded',
    'comparison.getFunded.desc': 'From application to cash in your account',
    'comparison.getFunded.traditional': '3-8 weeks',
    'comparison.getFunded.delt': '24 hours',
    'comparison.repayment': 'Repayment',
    'comparison.repayment.desc': 'How you pay back what you borrow',
    'comparison.repayment.traditional': 'Fixed monthly payment',
    'comparison.repayment.delt': '% of daily sales',
    'comparison.credit': 'Credit Requirement',
    'comparison.credit.desc': 'Minimum credit score needed to qualify',
    'comparison.credit.traditional': '680+ required',
    'comparison.credit.delt': '500+ accepted',
    'comparison.paperwork': 'Paperwork',
    'comparison.paperwork.desc': 'What you need to apply',
    'comparison.paperwork.traditional': 'Extensive documents',
    'comparison.paperwork.delt': 'Just link your bank',
    'comparison.paperwork.connectWith': 'Connect with',
    'comparison.slowMonths': 'Slow Months',
    'comparison.slowMonths.desc': 'What happens when sales are down',
    'comparison.slowMonths.traditional': 'Same high payment',
    'comparison.slowMonths.delt': 'Payment adjusts down',
    'comparison.collateral': 'Collateral',
    'comparison.collateral.desc': 'Assets you risk losing if you can\'t pay',
    'comparison.collateral.traditional': 'Required',
    'comparison.collateral.delt': 'None',

    // Wins Page
    'wins.badge': 'Client Success Stories',
    'wins.hero.title': 'Wins, Real Businesses',
    'wins.hero.real': 'Real',
    'wins.hero.subtitle': 'Discover how businesses just like yours achieved their growth goals with Delt Capital\'s Revenue-Based Financing',
    'wins.stats.totalCapital': 'Total Capital Deployed',
    'wins.stats.totalCapital.desc': 'Funded to small & mid-size businesses',
    'wins.stats.avgFunding': 'Average Funding Time',
    'wins.stats.avgFunding.desc': 'From application to funds received',
    'wins.stats.avgRevenue': 'Approval Rate',
    'wins.stats.avgRevenue.desc': 'Of qualified applicants funded',
    'wins.stats.satisfaction': 'Client Satisfaction',
    'wins.stats.satisfaction.desc': 'Average merchant rating',
    'wins.story.fundedAmount': 'Funded Amount',
    'wins.story.fundingDate': 'Funding Date',
    'wins.story.revenueGrowth': 'Revenue Growth',
    'wins.story.timeToFund': 'Time to Fund',
    'wins.story.newEmployees': 'New Employees',
    'wins.story.monthlyRevenue': 'Monthly Revenue',
    'wins.story.approvalTime': 'Approval Time',
    'wins.story.customerGrowth': 'Customer Growth',
    'wins.story.serviceExpansion': 'New Services',
    'wins.story.fundingSpeed': 'Funding Speed',
    'wins.story.clientBase': 'New Clients',
    'wins.story.fleetGrowth': 'Fleet Growth',
    'wins.story.revenueIncrease': 'Monthly Revenue Increase',
    'wins.story.processingTime': 'Processing Time',
    'wins.story.salesGrowth': 'Sales Growth',
    'wins.story.inventoryValue': 'Inventory Increase',
    'wins.story.fundedIn': 'Funded In',
    'wins.story.projectSize': 'Larger Project Capacity',
    'wins.story.teamGrowth': 'New Staff',
    'wins.cta.title': 'Ready to Write Your Success Story?',
    'wins.cta.your': 'Your',
    'wins.cta.subtitle': 'Join hundreds of businesses that have achieved their growth goals with Delt Capital',
    'wins.cta.button': 'Start Your Application',
    'wins.footer.disclaimer': 'All success stories are from actual Delt Capital clients. Individual results may vary based on business circumstances.',
  },
  es: {
    // Navbar
    'nav.apply': 'Aplicar Ahora',
    'nav.about': 'Sobre Nosotros',
    
    // Hero
    'hero.title': 'Capital Rápido y Flexible para su Negocio',
    'hero.subtitle': 'Obtenga el financiamiento que necesita con servicio personalizado. Aplique en minutos, reciba su oferta y acceda a fondos en 24-48 horas.',
    'hero.animated.capital': 'Capital',
    'hero.animated.moves': ' que se mueve a su ',
    'hero.animated.speed': 'ritmo',
    'hero.cta': 'Obtener su Oferta',
    'hero.instant': 'Decisiones Instantáneas',
    'hero.instantSub': 'Aprobación en minutos',
    'hero.amount': '$10K - $250K',
    'hero.amountSub': 'Montos flexibles',
    'hero.funding': 'Fondos en 24-48 Horas',
    'hero.fundingSub': 'Acceso rápido al capital',
    'hero.service': 'Servicio Personalizado',
    'hero.serviceSub': 'Equipo dedicado de apoyo',
    'hero.typicalFunding': 'Monto Típico de Financiamiento',
    'hero.appTime': 'Tiempo de Aplicación',
    'hero.appTime.value': '10-15 minutos',
    'hero.decisionTime': 'Tiempo de Decisión',
    'hero.decisionTime.value': 'Instantáneo - 4 horas',
    'hero.fundingSpeed': 'Velocidad de Financiamiento',
    'hero.fundingSpeed.value': '24-48 horas',
    'hero.approvalRate': 'Tasa Típica de Aprobación',
    
    // How It Works
    'how.title': 'Cómo Funciona',
    'how.subtitle': 'Obtenga el capital que necesita en cuatro simples pasos—rápido, transparente y sin complicaciones',
    'how.step1.title': 'Aplique en línea en minutos',
    'how.step1.desc': 'Proporcione información básica sobre su negocio y obtenga una decisión en minutos. Aplicar no afectará su puntaje de crédito.',
    'how.step2.title': 'Reciba su oferta de financiamiento instantáneo',
    'how.step2.desc': 'Sea aprobado y vea su oferta de financiamiento inmediatamente. Revise términos, tasas de factor y cronogramas de pago adaptados a su negocio.',
    'how.step3.title': 'Acceda a fondos en 24-48 horas',
    'how.step3.desc': 'Una vez que acepte, los fondos se depositan directamente en su cuenta comercial el siguiente día hábil—a menudo dentro de 24 horas.',
    'how.step4.title': 'Realice pagos automáticos',
    'how.step4.desc': 'Pague automáticamente basándose en un porcentaje de sus ventas diarias con tarjeta de crédito. Días de mayores ventas significan pagos más altos, días más lentos significan pagos más bajos.',
    
    // Use Capital
    'capital.title': 'Despliegue su Capital Estratégicamente',
    'capital.subtitle': 'Ya sea que esté escalando, invirtiendo o aprovechando una oportunidad, su capital puede impulsar el crecimiento en todo su negocio',
    'capital.payroll.title': 'Nómina y Contratación',
    'capital.payroll.desc': 'Traiga el talento que necesita para escalar sus operaciones y satisfacer la creciente demanda.',
    'capital.expansion.title': 'Expansión del Negocio',
    'capital.expansion.desc': 'Abra nuevas ubicaciones, expanda su presencia o actualice a una instalación más grande.',
    'capital.inventory.title': 'Inventario y Stock',
    'capital.inventory.desc': 'Compre inventario al por mayor, aproveche descuentos de proveedores o prepárese para la temporada alta.',
    'capital.marketing.title': 'Campañas de Marketing',
    'capital.marketing.desc': 'Invierta en publicidad, marketing digital o campañas promocionales para atraer nuevos clientes.',
    'capital.equipment.title': 'Equipo y Tecnología',
    'capital.equipment.desc': 'Actualice maquinaria, compre nuevo equipo o invierta en tecnología que mejore la eficiencia.',
    'capital.vendor.title': 'Pagos a Proveedores',
    'capital.vendor.desc': 'Pague a proveedores a tiempo, negocie mejores términos o aproveche descuentos por pago anticipado.',
    'capital.helpTitle': '¿No está seguro de lo que necesita? Estamos aquí para ayudar.',
    'capital.helpDesc': 'Nuestro equipo dedicado trabaja con usted para comprender sus objetivos comerciales y encontrar la solución de financiamiento adecuada. Obtenga orientación personalizada en cada paso.',
    'capital.hours': 'Lunes - Viernes, 8am - 8pm EST',
    
    // Guides
    'guides.title': 'Guías y Recursos Útiles',
    'guides.subtitle': 'Todo lo que necesita saber sobre adelantos de efectivo para comerciantes y financiamiento empresarial',
    'guides.calculator.title': 'Calculadora de Costo MCA',
    'guides.calculator.desc': 'Calcule el costo real de su adelanto de efectivo para comerciantes y compare tasas de factor.',
    'guides.qualification.title': 'Requisitos de Calificación',
    'guides.qualification.desc': 'Pre-califique y descubra qué buscan los prestamistas para mejorar sus posibilidades de aprobación.',
    'guides.repayment.title': 'Guía de Pago Basado en Ingresos',
    'guides.repayment.desc': 'Comprenda cómo los pagos diarios basados en porcentaje se adaptan al rendimiento de su negocio.',
    'guides.open': 'Abrir Herramienta',
    'guides.learn': 'Aprender más',
    
    // FAQ
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Obtenga respuestas a preguntas comunes sobre nuestro programa de adelanto de efectivo para comerciantes',
    'faq.q1': '¿Qué tan rápido puedo obtener mis fondos?',
    'faq.a1': 'Los tiempos de financiamiento varían según varios factores, incluida la completitud de la aplicación y el procesamiento de aprobación. Muchos solicitantes calificados reciben financiamiento dentro de 1-3 días hábiles después de la aprobación. Trabajamos diligentemente para procesar las aplicaciones lo más rápido posible mientras mantenemos nuestros estándares de suscripción.',
    'faq.q2': '¿Qué es una tasa de factor?',
    'faq.a2': 'Una tasa de factor es una cifra decimal utilizada para calcular el monto total de reembolso. En lugar de expresar el costo como una tasa de porcentaje anual, la tasa de factor se multiplica por el monto de su adelanto para determinar su reembolso total. Por ejemplo, una tasa de factor de 1.25 en un adelanto de $10,000 resultaría en un reembolso total de $12,500.',
    'faq.q3': '¿Cuáles son los términos de pago?',
    'faq.a3': 'El reembolso se estructura en función del flujo de efectivo de su negocio, típicamente a través de remesas automáticas diarias o semanales. El cronograma específico se determina durante el proceso de aprobación y se detalla en su acuerdo. Los términos están diseñados para alinearse con sus patrones de ingresos.',
    'faq.q4': '¿Qué necesito para aplicar?',
    'faq.a4': 'Los requisitos de aplicación típicamente incluyen información básica del negocio, estados de cuenta bancarios recientes y documentación de identificación. Nuestro proceso de aplicación está diseñado para ser sencillo. Un representante puede proporcionar una lista completa de materiales requeridos según su situación específica.',
    'faq.q5': '¿Para cuánto puedo calificar?',
    'faq.a5': 'Los montos de calificación varían según múltiples factores, incluido el desempeño financiero de su negocio, el tiempo en operación y los patrones de flujo de efectivo. Evaluamos cada aplicación individualmente para determinar un monto apropiado que se alinee con las necesidades y capacidad de su negocio.',
    'faq.q6': 'Tengo mal crédito. ¿Aún puedo calificar?',
    'faq.a6': 'Evaluamos las aplicaciones de manera integral, considerando varios aspectos de su negocio más allá de los puntajes de crédito personales. Si bien el historial crediticio es un factor, también evaluamos el desempeño del negocio, el flujo de efectivo y otros criterios relevantes. Le recomendamos que aplique para conocer sus opciones.',
    'faq.q7': '¿Hay tarifas ocultas?',
    'faq.a7': 'Todos los costos se divulgan en la documentación de su acuerdo antes de la aceptación. Mantenemos transparencia en nuestra estructura de tarifas. Revise cuidadosamente todos los términos del acuerdo y haga preguntas sobre cualquier elemento que requiera aclaración antes de continuar.',
    'faq.q8': '¿Qué sucede en días lentos?',
    'faq.a8': 'Las estructuras de reembolso están diseñadas teniendo en cuenta las fluctuaciones del negocio. Las disposiciones específicas con respecto a los períodos de ingresos variables se detallan en su acuerdo. Recomendamos discutir los patrones estacionales o cíclicos de su negocio con un representante durante el proceso de solicitud.',
    'faq.q9': '¿En qué se diferencia esto de un préstamo bancario?',
    'faq.a9': 'Nuestras soluciones de financiamiento difieren de los préstamos bancarios tradicionales en varios aspectos, incluidos los criterios de suscripción, la velocidad de financiamiento, la estructura de reembolso y los requisitos de garantía. Nos enfocamos en el desempeño y flujo de efectivo de su negocio en lugar de exclusivamente en puntajes de crédito y requisitos de documentación extensivos.',
    'faq.q10': '¿No es esto caro?',
    'faq.a10': 'El costo varía según las circunstancias individuales y el producto específico. Al evaluar opciones de financiamiento, considere factores más allá del costo solo, incluida la velocidad de acceso, los requisitos de calificación y la alineación con las necesidades de su negocio. Le recomendamos que compare los costos totales y los términos entre todas las opciones disponibles para usted.',
    'faq.stillQuestions': '¿Todavía tiene preguntas?',
    'faq.callUs': 'Llámenos: (864) 729-3358',
    
    // CTA
    'cta.title': '¿Listo para crecer?',
    'cta.subtitle': '¿Quiere saber más?\nExplore nuestros Recursos y Guías.',
    'cta.button': 'Comenzar',
    'cta.minutes': '10-15 Minutos',
    'cta.minutesSub': 'Proceso de aplicación rápido',
    'cta.instant': 'Decisión Instantánea',
    'cta.instantSub': 'Aprobado en minutos',
    'cta.hours': '24-48 Horas',
    'cta.hoursSub': 'Fondos en su cuenta',
    
    // Footer
    'footer.company': 'Compañía',
    'footer.about': 'Sobre Nosotros',
    'footer.howItWorks': 'Cómo Funciona',
    'footer.reviews': 'Reseñas',
    'footer.blog': 'Blog',
    'footer.resources': 'Recursos',
    'footer.faq': 'Preguntas Frecuentes',
    'footer.calculator': 'Calculadora',
    'footer.caseStudies': 'Casos de Estudio',
    'footer.support': 'Centro de Ayuda',
    'footer.contact': 'Contacto',
    'footer.hours': 'Lun-Vie, 8am-8pm EST',
    'footer.description': 'Adelantos de efectivo rápidos y flexibles con servicio personalizado y términos transparentes.',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.disclosures': 'Divulgaciones',
    'footer.disclaimer': 'Delt proporciona adelantos de efectivo para comerciantes, que no son préstamos. Los adelantos de efectivo para comerciantes son transacciones de negocio a negocio y no están sujetos a las mismas regulaciones que los préstamos de consumo. Aprobación y términos basados en el rendimiento del negocio. Solo para fines de demostración.',
    
    // About Page
    'about.title': 'Sobre Delt',
    'about.subtitle': 'Empoderando negocios con soluciones de financiamiento rápidas y flexibles',
    'about.hero.title': 'Estamos en una misión para democratizar el acceso al capital empresarial',
    'about.hero.desc': 'Fundada en 2020, Delt ha ayudado a miles de pequeñas y medianas empresas a acceder al capital que necesitan para crecer, sin las barreras tradicionales del financiamiento bancario.',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.desc': 'Proporcionar soluciones de financiamiento rápidas, transparentes y flexibles que ayuden a las empresas a aprovechar oportunidades y superar desafíos.',
    'about.values.title': 'Nuestros Valores',
    'about.values.speed': 'Velocidad',
    'about.values.speedDesc': 'Decisiones en minutos, fondos en días',
    'about.values.transparency': 'Transparencia',
    'about.values.transparencyDesc': 'Sin tarifas ocultas, términos claros',
    'about.values.flexibility': 'Flexibilidad',
    'about.values.flexibilityDesc': 'Pagos que se adaptan a su negocio',
    'about.values.service': 'Servicio',
    'about.values.serviceDesc': 'Apoyo personalizado en cada paso',
    'about.stats.funded': 'Negocios Financiados',
    'about.stats.capital': 'Capital Desplegado',
    'about.stats.approval': 'Tasa de Aprobación',
    'about.stats.satisfaction': 'Satisfacción del Cliente',
    'about.team.title': 'Construido por expertos en fintech',
    'about.team.desc': 'Nuestro equipo aporta décadas de experiencia de instituciones financieras líderes y empresas de tecnología.',
    'about.cta': '¿Listo para comenzar?',
    'about.apply': 'Aplicar Ahora',
    
    // PreQualification Quiz
    'quiz.q1.question': '¿Cuál es su ingreso mensual promedio?',
    'quiz.q1.subtitle': 'Esto nos ayuda a determinar su capacidad de financiamiento',
    'quiz.q1.opt1': 'Menos de $10,000/mes',
    'quiz.q1.opt2': '$10,000 - $25,000/mes',
    'quiz.q1.opt3': '$25,000 - $50,000/mes',
    'quiz.q1.opt4': '$50,000 - $100,000/mes',
    'quiz.q1.opt5': '$100,000+/mes',
    
    'quiz.q2.question': '¿Cuánto tiempo lleva operando su negocio?',
    'quiz.q2.subtitle': 'Las empresas establecidas suelen calificar para mejores términos',
    'quiz.q2.opt1': 'Menos de 6 meses',
    'quiz.q2.opt2': '6-12 meses',
    'quiz.q2.opt3': '1-2 años',
    'quiz.q2.opt4': '2-5 años',
    'quiz.q2.opt5': '5+ años',
    
    'quiz.q3.question': '¿Cuál es su volumen mensual de procesamiento de tarjetas de crédito?',
    'quiz.q3.subtitle': 'Los MCA se pagan a través de ventas con tarjeta, por lo que esto es crucial',
    'quiz.q3.opt1': 'Sin procesamiento de tarjetas de crédito',
    'quiz.q3.opt2': 'Menos de $5,000/mes',
    'quiz.q3.opt3': '$5,000 - $15,000/mes',
    'quiz.q3.opt4': '$15,000 - $40,000/mes',
    'quiz.q3.opt5': '$40,000+/mes',
    
    'quiz.q4.question': '¿Cuál es el rango de su puntaje de crédito personal?',
    'quiz.q4.subtitle': 'Se utiliza para decisiones de aprobación y precios',
    'quiz.q4.opt1': 'Menos de 550',
    'quiz.q4.opt2': '550-599',
    'quiz.q4.opt3': '600-649',
    'quiz.q4.opt4': '650-699',
    'quiz.q4.opt5': '700+',
    
    'quiz.q5.question': '¿Cuánto financiamiento necesita?',
    'quiz.q5.subtitle': 'Ofrecemos adelantos de $10,000 a $250,000',
    'quiz.q5.opt1': '$10,000 - $25,000',
    'quiz.q5.opt2': '$25,000 - $50,000',
    'quiz.q5.opt3': '$50,000 - $100,000',
    'quiz.q5.opt4': '$100,000 - $150,000',
    'quiz.q5.opt5': '$150,000+',
    
    'quiz.q6.question': '¿Para qué usará los fondos?',
    'quiz.q6.subtitle': 'Comprender sus necesidades nos ayuda a servirle mejor',
    'quiz.q6.opt1': 'Compra de Inventario',
    'quiz.q6.opt2': 'Equipo o Tecnología',
    'quiz.q6.opt3': 'Marketing y Crecimiento',
    'quiz.q6.opt4': 'Capital de Trabajo',
    'quiz.q6.opt5': 'Expansión del Negocio',
    'quiz.q6.opt6': 'Otras Necesidades del Negocio',
    
    'quiz.progress': 'Pregunta {{current}} de {{total}}',
    'quiz.next': 'Siguiente',
    'quiz.previous': 'Anterior',
    'quiz.seeResults': 'Ver Resultados',
    
    // Quiz Results
    'results.title': '¡Felicitaciones! Usted Pre-Califica',
    'results.subtitle': 'Basado en sus respuestas, estimamos que califica para:',
    'results.fundingEstimate': 'Estimación de Financiamiento',
    'results.to': 'a',
    'results.nextSteps': 'Próximos Pasos',
    'results.step1': 'Complete su aplicación completa',
    'results.step2': 'Conecte su banco y procesador de tarjetas',
    'results.step3': 'Reciba su oferta final en minutos',
    'results.step4': 'Fondos en su cuenta en 24-48 horas',
    'results.benefits': 'Sus Beneficios',
    'results.benefit1': 'Decisión Instantánea',
    'results.benefit1desc': 'Respuesta en minutos',
    'results.benefit2': 'Sin Papeleo',
    'results.benefit2desc': 'Proceso 100% digital',
    'results.benefit3': 'Pagos Flexibles',
    'results.benefit3desc': 'Basado en sus ventas',
    'results.benefit4': 'Fondos Rápidos',
    'results.benefit4desc': '24-48 horas',
    'results.continue': 'Continuar con la Aplicación',
    
    // Application Form
    'app.businessInfo': 'Información del Negocio',
    'app.businessInfo.desc': 'Cuéntenos sobre su negocio',
    'app.ownerInfo': 'Información del Propietario',
    'app.ownerInfo.desc': 'Información del propietario principal',
    'app.fundingDetails': 'Detalles del Financiamiento',
    'app.fundingDetails.desc': 'Monto y uso de los fondos',
    'app.bankConnection': 'Conexión Bancaria',
    'app.bankConnection.desc': 'Conexión segura de datos',
    'app.documents': 'Documentos',
    'app.documents.desc': 'Cargue los documentos requeridos',
    'app.review': 'Revisar y Firmar',
    'app.review.desc': 'Revise y complete',
    
    'app.businessLegalName': 'Nombre Legal del Negocio',
    'app.businessDBA': 'DBA/Nombre Comercial',
    'app.businessAddress': 'Dirección del Negocio',
    'app.businessCity': 'Ciudad',
    'app.businessState': 'Estado',
    'app.businessZip': 'Código Postal',
    'app.businessPhone': 'Teléfono del Negocio',
    'app.businessEIN': 'EIN (Número de Identificación del Empleador)',
    'app.industry': 'Industria',
    'app.timeInBusiness': 'Tiempo en el Negocio',
    'app.monthlyRevenue': 'Ingreso Mensual',
    'app.creditCardProcessing': 'Volumen de Tarjeta de Crédito',
    'app.creditScore': 'Rango de Puntaje de Crédito',
    
    'app.ownerFullName': 'Nombre Completo del Propietario',
    'app.ownerEmail': 'Correo Electrónico',
    'app.ownerPhone': 'Número de Teléfono',
    'app.ownerAddress': 'Dirección',
    'app.ownerCity': 'Ciudad',
    'app.ownerState': 'Estado',
    'app.ownerZip': 'Código Postal',
    'app.ownerSSN': 'Últimos 4 Dígitos del SSN',
    
    'app.requestedAmount': 'Monto Solicitado',
    'app.intendedUse': 'Uso Previsto de los Fondos',
    'app.intendedUse.placeholder': 'Describa cómo usará los fondos...',
    
    'app.connectBank': 'Conectar Cuenta Bancaria',
    'app.connectBank.desc': 'Conecte de forma segura su banco para verificación instantánea',
    'app.connectBank.button': 'Conectar con Plaid',
    'app.bankConnected': '✓ Banco Conectado',
    'app.creditCardProcessor': 'Procesador de Tarjetas de Crédito',
    'app.uploadStatements': 'Cargar Estados de Cuenta del Procesador',
    'app.uploadStatements.desc': 'Últimos 3 meses de estados de cuenta',
    
    'app.governmentID': 'Identificación Emitida por el Gobierno',
    'app.governmentID.desc': 'Licencia de conducir, pasaporte, etc.',
    'app.voidedCheck': 'Cheque Anulado',
    'app.voidedCheck.desc': 'Para verificación de cuenta bancaria',
    'app.dragDrop': 'Arrastre y suelte archivos aquí, o haga clic para seleccionar',
    'app.fileSelected': 'archivo seleccionado',
    'app.filesSelected': 'archivos seleccionados',
    
    'app.reviewTitle': 'Revisar su Aplicación',
    'app.reviewDesc': 'Por favor revise su información antes de enviar',
    'app.businessDetails': 'Detalles del Negocio',
    'app.ownerDetails': 'Detalles del Propietario',
    'app.fundingRequest': 'Solicitud de Financiamiento',
    'app.amount': 'Monto',
    'app.purpose': 'Propósito',
    
    'app.termsAgree': 'Acepto los Términos y Condiciones y autorizo a Delt a obtener mi informe de crédito',
    'app.eSignature': 'Firma Electrónica',
    'app.eSignature.placeholder': 'Escriba su nombre completo',
    'app.eSignature.desc': 'Al escribir su nombre arriba, acepta electrónicamente los términos de este acuerdo',
    
    'app.saveProgress': 'Guardar y Continuar Más Tarde',
    'app.continue': 'Continuar',
    'app.back': 'Atrás',
    'app.submit': 'Enviar Aplicación',
    
    // Success Messages
    'success.title': '¡Aplicación Enviada Exitosamente!',
    'success.subtitle': 'Estamos revisando su aplicación y nos pondremos en contacto pronto.',
    'success.reference': 'Número de Referencia',
    'success.whatNext': '¿Qué Sigue?',
    'success.step1.title': 'Revisión Instantánea',
    'success.step1.desc': 'Nuestro equipo está revisando su aplicación ahora',
    'success.step2.title': 'Verificación',
    'success.step2.desc': 'Verificaremos su información bancaria y de negocio',
    'success.step3.title': 'Oferta Final',
    'success.step3.desc': 'Recibirá su oferta de financiamiento en 2-4 horas',
    'success.step4.title': 'Financiamiento',
    'success.step4.desc': 'Acepte su oferta y reciba fondos en 24-48 horas',
    'success.contact': 'Preguntas? Llámenos al',
    'success.done': 'Hecho',
    
    // Calculator
    'calc.title': 'Calculadora de Costo MCA',
    'calc.subtitle': 'Analice el costo verdadero de su Adelanto de Efectivo para Comerciantes',
    'calc.advanceAmount': 'Monto del Adelanto',
    'calc.factorRate': 'Tasa de Factor',
    'calc.paybackAmount': 'Monto de Reembolso Total',
    'calc.totalCost': 'Costo Total',
    'calc.paybackPeriod': 'Período de Reembolso',
    'calc.paybackPeriod.months': 'meses',
    'calc.dailyPayment': 'Pago Diario Estimado',
    'calc.effectiveAPR': 'APR Efectivo',
    'calc.costBreakdown': 'Desglose de Costos',
    'calc.principalAmount': 'Monto Principal',
    'calc.totalInterest': 'Interés Total/Cargo',
    'calc.comparison': 'Comparación',
    'calc.traditionalLoan': 'Préstamo Tradicional',
    'calc.mca': 'Adelanto de Efectivo Comercial',
    'calc.calculate': 'Calcular',
    
    // Additional Quiz/Form UI
    'quiz.complete': 'Completo',
    'quiz.back': 'Atrás',
    'quiz.startApp': 'Comenzar su Aplicación',
    'quiz.speakSpecialist': 'Hablar con un Especialista',
    
    // Application
    'application.savedAnswers': 'Guardamos sus respuestas',
    
    // Results Page Detailed
    'results.fundingRange': 'Su Rango de Financiamiento Estimado',
    'results.basedOnProfile': 'Basado en el perfil de su negocio',
    'results.approvalLikelihood': 'Probabilidad de Aprobación',
    'results.factorsConsidered': 'Factores Considerados',
    'results.whatHappensNext': 'Qué Sucede Después',
    'results.completeApp': 'Complete Su Aplicación',
    'results.completeApp.time': 'Toma 10-15 minutos',
    'results.instantReview': 'Revisión Instantánea',
    'results.instantReview.desc': 'La IA analiza su negocio en tiempo real',
    'results.getFunded': 'Obtenga Fondos',
    'results.getFunded.desc': 'Dinero en su cuenta en 24-48 horas',
    'results.disclaimer': 'Esta es una estimación basada en la información proporcionada. Los montos de financiamiento finales y los términos están sujetos a aprobación y verificación de la información de su negocio, historial crediticio y documentos financieros.',
    
    // Transition Phase
    'transition.title': '¡Buenas Noticias! Usted Pre-Califica',
    'transition.subtitle': 'Completemos su aplicación para finalizar su oferta',
    'transition.whatWeKnow': 'Esto es lo que ya sabemos:',
    'transition.fundingAmount': 'Monto de Financiamiento',
    'transition.monthlyRevenue': 'Ingreso Mensual',
    'transition.timeInBusiness': 'Tiempo en el Negocio',
    'transition.nextStep': 'A continuación, necesitaremos:',
    'transition.businessDetails': 'Detalles del Negocio',
    'transition.ownerInfo': 'Información del Propietario',
    'transition.bankConnection': 'Conexión Bancaria',
    'transition.autoRedirect': 'Redirigiendo automáticamente...',
    
    // Form Steps
    'form.step.basicInfo': 'Información Básica',
    'form.step.ownerInfo': 'Información del Propietario',
    'form.step.fundingRequest': 'Solicitud de Financiamiento',
    'form.step.connectAccounts': 'Conectar Cuentas',
    'form.step.uploadDocs': 'Cargar Documentos',
    'form.step.reviewSubmit': 'Revisar y Enviar',
    
    // Industry Options
    'industry.restaurant': 'Restaurante / Servicio de Alimentos',
    'industry.retail': 'Comercio Minorista',
    'industry.healthcare': 'Atención Médica',
    'industry.professional': 'Servicios Profesionales',
    'industry.construction': 'Construcción',
    'industry.transportation': 'Transporte',
    'industry.manufacturing': 'Manufactura',
    'industry.technology': 'Tecnología',
    'industry.hospitality': 'Hospitalidad',
    'industry.realEstate': 'Bienes Raíces',
    'industry.other': 'Otro',
    
    // Funding Uses
    'use.workingCapital': 'Capital de Trabajo',
    'use.inventory': 'Compra de Inventario',
    'use.equipment': 'Compra de Equipo',
    'use.marketing': 'Marketing / Publicidad',
    'use.expansion': 'Expansión / Crecimiento',
    'use.payroll': 'Nómina',
    'use.debtConsolidation': 'Consolidación de Deudas',
    'use.renovations': 'Renovaciones',
    'use.emergency': 'Gastos de Emergencia',
    'use.other': 'Otro',
    
    // Credit Card Processors
    'processor.square': 'Square',
    'processor.clover': 'Clover',
    'processor.toast': 'Toast',
    'processor.stripe': 'Stripe',
    'processor.paypal': 'PayPal',
    'processor.shopify': 'Shopify Payments',
    'processor.authorizenet': 'Authorize.net',
    'processor.firstdata': 'First Data',
    'processor.worldpay': 'Worldpay',
    'processor.other': 'Otro',
    
    // MCA Knowledge Center
    'knowledge.title': 'Centro de Conocimientos de Adelanto de Efectivo',
    'knowledge.subtitle': 'Todo lo que necesita saber sobre adelantos de efectivo para comerciantes',
    'knowledge.howItWorks': 'Cómo Funciona',
    'knowledge.howToApply': 'Cómo Aplicar',
    'knowledge.managingRepayment': 'Gestión de Reembolso',
    
    // How It Works Tab
    'knowledge.whatIsMCA': '¿Qué es un Adelanto de Efectivo?',
    'knowledge.whatIsMCA.desc': 'Obtenga capital ahora. Pague automáticamente de las ventas diarias con tarjeta. Días de altas ventas = pagos más altos. Días lentos = pagos más bajos.',
    'knowledge.3steps': '3 Pasos Simples',
    'knowledge.step1.title': 'Obtenga Fondos',
    'knowledge.step1.desc': 'Dinero en su cuenta en 1-3 días',
    'knowledge.step2.title': 'Reembolso Automático',
    'knowledge.step2.desc': '% Fijo de ventas con tarjeta va al reembolso',
    'knowledge.step3.title': 'Completado',
    'knowledge.step3.desc': 'La retención se detiene cuando se paga',
    'knowledge.keyTerms': 'Términos Clave',
    'knowledge.purchaseAmount': 'Monto de Compra',
    'knowledge.purchaseAmount.desc': 'Lo que usted recibe',
    'knowledge.holdback': 'Porcentaje de Retención',
    'knowledge.holdback.desc': 'Porción diaria hacia el reembolso (10-20%)',
    'knowledge.factorRate': 'Tasa de Factor',
    'knowledge.factorRate.desc': 'Multiplicador de reembolso (1.15-1.45)',
    'knowledge.goodFit': '¿Es Adecuado?',
    'knowledge.yesIf': 'Sí si tiene:',
    'knowledge.yes1': 'Ventas constantes con tarjeta de crédito',
    'knowledge.yes2': 'Negocio de comercio minorista/restaurante/salón/servicio',
    'knowledge.yes3': 'Necesita capital rápido',
    'knowledge.notIdeal': 'No es ideal si:',
    'knowledge.no1': 'Mayormente negocio en efectivo',
    'knowledge.no2': 'Ventas con tarjeta muy irregulares',
    
    // How to Apply Tab
    'knowledge.youNeed': 'Usted Necesita:',
    'knowledge.connectPlaid': 'Conectar a Plaid',
    'knowledge.connectPlaid.desc': 'Verificación bancaria instantánea segura',
    'knowledge.processingStatements': 'Subir Estados de Cuenta de Procesamiento',
    'knowledge.processingStatements.desc': 'Últimos 3-4 meses',
    'knowledge.businessInfo': 'Agregar información del negocio',
    'knowledge.businessInfo.desc': 'ID, nombre legal, dirección, ID fiscal',
    'knowledge.weLookFor': 'Buscamos:',
    'knowledge.look1': 'Volumen de tarjeta consistente',
    'knowledge.look2': 'Transacciones regulares',
    'knowledge.look3': 'Contracargos mínimos',
    'knowledge.quickTips': 'Consejos Rápidos:',
    'knowledge.tip1': 'Tenga documentos listos (PDF/imagen)',
    'knowledge.tip2': 'Verifique todos los detalles por precisión',
    'knowledge.tip3': 'No Aplique en Todos Lados a la Vez',
    'knowledge.timeline': 'Cronograma:',
    'knowledge.timeline.desc': 'Aplicación: 15 min • Revisión: 24-48 hrs • Financiamiento: 1-3 días',
    
    // Managing Repayment Tab
    'knowledge.firstSteps': 'Primeros Pasos',
    'knowledge.first1': 'Verificar retención con el procesador',
    'knowledge.first2': 'Monitorear remesas diarias',
    'knowledge.first3': 'Desplegar fondos estratégicamente',
    'knowledge.knowThis': 'Sepa Esto:',
    'knowledge.know1': 'Los pagos varían diariamente según las ventas con tarjeta',
    'knowledge.know2': 'Pago típico: 6-12 meses',
    'knowledge.know3': 'Rastree su saldo — Solicite actualizaciones en cualquier momento',
    'knowledge.smartMoves': 'Movimientos Inteligentes',
    'knowledge.useFundsFor': 'Usar fondos para:',
    'knowledge.use1': 'Inventario',
    'knowledge.use2': 'Equipo',
    'knowledge.use3': 'Marketing',
    'knowledge.use4': 'Brechas de flujo de efectivo',
    'knowledge.maintain': 'Mantener:',
    'knowledge.maintain.desc': 'Relación con el procesador primario',
    'knowledge.plan': 'Planificar:',
    'knowledge.plan.desc': 'Flujo de efectivo diario con retención considerada',
    'knowledge.futureFunding': 'Financiamiento Futuro',
    'knowledge.future1': 'Reembolso exitoso = mejores términos futuros',
    'knowledge.future2': 'Vuelva a aplicar después del 50-75% pagado',
    'knowledge.questions': '¿Preguntas?',
    'knowledge.questions.desc': 'Contacte soporte para saldo, retención o ayuda con la cuenta.',

    // Stats Section
    'stats.capitalDelivered': 'capital de trabajo entregado',
    'stats.businessesFunded': 'Negocios Financiados',
    'stats.satisfactionRate': 'Tasa de Satisfacción',
    'stats.avgFundingTime': 'Tiempo Promedio de Financiamiento',
    'stats.averageAdvance': 'Anticipo Promedio',
    'stats.joinText': 'Únase a más de 2,850 empresas estadounidenses a las que hemos ayudado con soluciones de financiamiento personalizadas.',
    'stats.industryText': 'Desde restaurantes y tiendas minoristas hasta servicios profesionales y proveedores de atención médica, nos hemos asociado con empresas de todas las industrias para impulsar su crecimiento con capital rápido y flexible.',
    'stats.disclaimer': 'Delt ofrece soluciones de financiamiento comercial, incluyendo anticipos de efectivo para comerciantes. El financiamiento puede ser proporcionado directamente por Delt o a través de socios de financiamiento externos.',

    // Pre-Qualification Section
    'preQual.title': '¿Se Pregunta Si Califica?',
    'preQual.subtitle': 'Descúbralo instantáneamente.',
    'preQual.questions': 'Responda 6 preguntas para desbloquear:',
    'preQual.probability': 'Su probabilidad de aprobación',
    'preQual.estimatedFunding': 'Monto de financiamiento estimado',
    'preQual.expectedPricing': 'Precio esperado',
    'preQual.button': 'Obtenga Mi Monto de Financiamiento',
    'preQual.noCredit': 'Sin impacto en el crédito',
    'preQual.instantResults': 'Resultados instantáneos',
    'preQual.joinText': 'Únase a más de 2,850 negocios que han verificado su calificación',

    // Comparison Table
    'comparison.title': 'Por Qué las Empresas Eligen',
    'comparison.delt': 'Delt',
    'comparison.overLoans': 'Sobre Préstamos Tradicionales',
    'comparison.subtitle': 'Vea cómo nos comparamos con los préstamos bancarios tradicionales',
    'comparison.feature': 'Característica',
    'comparison.traditional': 'Bancos Tradicionales',
    'comparison.delt.capital': 'Delt Capital',
    'comparison.getFunded': 'Obtener Fondos',
    'comparison.getFunded.desc': 'Desde la aplicación hasta el efectivo en su cuenta',
    'comparison.getFunded.traditional': '3-8 semanas',
    'comparison.getFunded.delt': '24 horas',
    'comparison.repayment': 'Reembolso',
    'comparison.repayment.desc': 'Cómo devuelve lo que pide prestado',
    'comparison.repayment.traditional': 'Pago mensual fijo',
    'comparison.repayment.delt': '% de ventas diarias',
    'comparison.credit': 'Requisito de Crédito',
    'comparison.credit.desc': 'Puntaje de crédito mínimo necesario para calificar',
    'comparison.credit.traditional': '680+ requerido',
    'comparison.credit.delt': '500+ aceptado',
    'comparison.paperwork': 'Papeleo',
    'comparison.paperwork.desc': 'Lo que necesita para aplicar',
    'comparison.paperwork.traditional': 'Documentos extensos',
    'comparison.paperwork.delt': 'Solo vincule su banco',
    'comparison.paperwork.connectWith': 'Conectar con',
    'comparison.slowMonths': 'Meses Lentos',
    'comparison.slowMonths.desc': 'Qué sucede cuando las ventas están bajas',
    'comparison.slowMonths.traditional': 'Mismo pago alto',
    'comparison.slowMonths.delt': 'El pago se ajusta hacia abajo',
    'comparison.collateral': 'Garantía',
    'comparison.collateral.desc': 'Activos que arriesga perder si no puede pagar',
    'comparison.collateral.traditional': 'Requerida',
    'comparison.collateral.delt': 'Ninguna',

    // Wins Page
    'wins.badge': 'Historias de Éxito de Clientes',
    'wins.hero.title': 'Victorias, Negocios Reales',
    'wins.hero.real': 'Reales',
    'wins.hero.subtitle': 'Descubra cómo negocios como el suyo lograron sus objetivos de crecimiento con el Financiamiento Basado en Ingresos de Delt Capital',
    'wins.stats.totalCapital': 'Capital Total Desplegado',
    'wins.stats.totalCapital.desc': 'Financiado a pequeñas y medianas empresas',
    'wins.stats.avgFunding': 'Tiempo Promedio de Financiamiento',
    'wins.stats.avgFunding.desc': 'Desde la aplicación hasta los fondos recibidos',
    'wins.stats.avgRevenue': 'Tasa de Aprobación',
    'wins.stats.avgRevenue.desc': 'De solicitantes calificados financiados',
    'wins.stats.satisfaction': 'Satisfacción del Cliente',
    'wins.stats.satisfaction.desc': 'Calificación promedio de comerciantes',
    'wins.story.fundedAmount': 'Monto Financiado',
    'wins.story.fundingDate': 'Fecha de Financiamiento',
    'wins.story.revenueGrowth': 'Crecimiento de Ingresos',
    'wins.story.timeToFund': 'Tiempo para Financiar',
    'wins.story.newEmployees': 'Nuevos Empleados',
    'wins.story.monthlyRevenue': 'Ingresos Mensuales',
    'wins.story.approvalTime': 'Tiempo de Aprobación',
    'wins.story.customerGrowth': 'Crecimiento de Clientes',
    'wins.story.serviceExpansion': 'Nuevos Servicios',
    'wins.story.fundingSpeed': 'Velocidad de Financiamiento',
    'wins.story.clientBase': 'Nuevos Clientes',
    'wins.story.fleetGrowth': 'Crecimiento de Flota',
    'wins.story.revenueIncrease': 'Aumento Mensual de Ingresos',
    'wins.story.processingTime': 'Tiempo de Procesamiento',
    'wins.story.salesGrowth': 'Crecimiento de Ventas',
    'wins.story.inventoryValue': 'Aumento de Inventario',
    'wins.story.fundedIn': 'Financiado En',
    'wins.story.projectSize': 'Mayor Capacidad de Proyectos',
    'wins.story.teamGrowth': 'Nuevo Personal',
    'wins.cta.title': '¿Listo para Escribir Su Historia de Éxito?',
    'wins.cta.your': 'Su',
    'wins.cta.subtitle': 'Únase a cientos de negocios que han logrado sus objetivos de crecimiento con Delt Capital',
    'wins.cta.button': 'Comience Su Aplicación',
    'wins.footer.disclaimer': 'Todas las historias de éxito son de clientes reales de Delt Capital. Los resultados individuales pueden variar según las circunstancias del negocio.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language | null;
    if (savedLanguage) {
      setLanguage(savedLanguage);
    } else {
      setLanguage('en');
      localStorage.setItem('language', 'en');
    }
  }, []);

  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'es' : 'en';
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
